### ISSUE TITLE
Непонятка в контенте с типом трек

### ISSUE THREAD

**Issue by rdddra** [konclave/retroisland#14]
Пишет, что их найдено 1486 штук. Но увидеть все я не могу. Показывает только штук 50.  Мне нужно удалить трек "Синева". Как мне его найти?

**Comment by konclave** [comment]
@rdddra Нужно выбрать тип контента `Track` и вбить в поиске то, что ты хочешь найти.

https://user-images.githubusercontent.com/875116/210426458-15681683-42eb-430a-b996-6f949a11bd85.mov

**Comment by rdddra** [comment]
А просто двигаться по списку нельзя?

**Comment by konclave** [comment]
Можно. Внизу списка кнопочки есть
<img width="446" alt="SCR-20230105-juo" src="https://user-images.githubusercontent.com/875116/210789001-534bfb49-42db-43fd-893f-875994fd01c9.png">

**Comment by rdddra** [comment]
Понял, можно закрывать
