### ISSUE TITLE
Новые колонки в представлении

### ISSUE THREAD

**Issue by rdddra** [konclave/retroisland#15]
Как сделать так, чтобы колонка, которую я добавляю в таблицу контента (делаю видимой) оставалась на следующий сеанс?

**Comment by konclave** [comment]
Я завел еще одного пользователя с правами редактора, чтобы проверить, и всё сохраняется. 
Ты из одного и того же браузера и с одного и того же компа заходишь?

**Comment by rdddra** [comment]
Да, теперь, вроде, сохраняется.
