### ISSUE TITLE
Контент с типом контента "Внешняя ссылка"

### ISSUE THREAD

**Issue by rdddra** [konclave/retroisland#16]
Почему-то в этот тип попали записи с внутренними ссылками.

**Comment by konclave** [comment]
Да, я посмотрел, туда попали некоторые аудиофайлы типа wav и m4a. 
Я так понимаю, что ты уже начал контент править? 
Если да, то проще руками всё это поправить, если нет, то могу скрипт поправить и залить весь контент ещё раз

**Comment by rdddra** [comment]
Я пока информацию вношу и туда и туда, поэтому можно перезалить.
