### ISSUE TITLE
Видео

### ISSUE THREAD

**Issue by rdddra** [konclave/retroisland#17]
Они получились "слепые", без подписей.   А в подписях были Исполнители, название и главное дата.
Нет возможности как-то добавить информацию?
А если я видео помещу в треки, что будет?

**Comment by konclave** [comment]
Вообще, там в данных видео есть подписи, так что их можно показывать, только надо придумать как это делать, чтобы смотрелось нормально. 
В треки их переместить не получится – просто ничего не будет работать
