### ISSUE TITLE
Возможность скачивать

### ISSUE THREAD

**Issue by rdddra** [konclave/retroisland#18]
Можно ли добавить возможность скачивать треки?  Это будет правильно.

**Comment by konclave** [comment]
Да, можно. Добавлю иконку где-нибудь рядом с треком. 
Это нужно только в каталоге, или в "по запросу" тоже?

**Comment by rdddra** [comment]
Лучше всюду.  Сайт для того и сделан, чтобы можно было получить все к себе в коллекцию.

**Comment by konclave** [comment]
Тут есть нюанс, что больше никто ничего никуда не сохраняет. Всё потребление контента теперь ушло в стриминги и онлайн. 
Механика типа "скачал, потом слушаешь" уже не очень работает.
