### ISSUE TITLE
Видео "Про Битлз" 

### ISSUE THREAD

**Issue by rdddra** [konclave/retroisland#19]
Высвечивает два элемента, один (с Ютуба) не  привязан ни к чему. Не вижу, как удалить.

**Comment by konclave** [comment]
<img width="1624" alt="SCR-20230109-lep" src="https://user-images.githubusercontent.com/875116/211331270-6430a673-d543-49b4-8905-6aaefc733e45.png">

**Comment by rdddra** [comment]
Ок, попробую
