### ISSUE TITLE
Полный каталог

### ISSUE THREAD

**Issue by rdddra** [konclave/retroisland#27]
Когда раскрываешь каталог, то пропадают разделы внизу:  по заявкам, гостевая книга.
Можно ли сделать так, чтобы они оставались?

И картотеку можно по-алфавиту расположить?

**Comment by konclave** [comment]
Это ты не раскрываешь каталог, это ты переходишь на новую страничку, поэтому всё пропадает. 

Да, сортировку можно поменять. Сделаю чтобы было по алфавиту

**Comment by konclave** [comment]
Я поменял сортировку, но подумал, может нужно сортировать по алфавиту не "имя фамилия", а по фамилии?
